CREATE TABLE users (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL,
    user_type TEXT NOT NULL DEFAULT 'cliente'::text,
    plan_type INTEGER DEFAULT 0,
    is_premium BOOLEAN DEFAULT false,
    last_generation TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
    
    -- Si estás usando Supabase, normalmente la FK iría hacia auth.users
    -- CONSTRAINT fk_users_auth FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE TABLE custom_citation_formats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    font_family VARCHAR(50) NOT NULL DEFAULT 'Times New Roman'::character varying,
    font_size INTEGER NOT NULL DEFAULT 12,
    font_color VARCHAR(10) NOT NULL DEFAULT '#000000'::character varying,
    text_alignment VARCHAR(20) NOT NULL DEFAULT 'Justified'::character varying,
    line_spacing NUMERIC NOT NULL DEFAULT 2.00,
    paragraph_before NUMERIC NOT NULL DEFAULT 0,
    paragraph_after NUMERIC NOT NULL DEFAULT 0,
    first_line_indent NUMERIC NOT NULL DEFAULT 1.27,
    left_indent NUMERIC NOT NULL DEFAULT 0,
    right_indent NUMERIC NOT NULL DEFAULT 0,
    margin_top NUMERIC NOT NULL DEFAULT 2.54,
    margin_bottom NUMERIC NOT NULL DEFAULT 2.54,
    margin_left NUMERIC NOT NULL DEFAULT 2.54,
    margin_right NUMERIC NOT NULL DEFAULT 2.54,
    paper_size VARCHAR(20) NOT NULL DEFAULT 'Letter'::character varying,
    orientation VARCHAR(20) NOT NULL DEFAULT 'Portrait'::character varying,
    header_distance NUMERIC NOT NULL DEFAULT 1.27,
    footer_distance NUMERIC NOT NULL DEFAULT 1.27,
    page_number_enabled BOOLEAN NOT NULL DEFAULT true,
    page_number_position VARCHAR(30) NOT NULL DEFAULT 'TopRight'::character varying,
    heading1_size INTEGER NOT NULL DEFAULT 16,
    heading1_bold BOOLEAN NOT NULL DEFAULT true,
    heading1_italic BOOLEAN NOT NULL DEFAULT false,
    heading1_alignment VARCHAR(20) NOT NULL DEFAULT 'Left'::character varying,
    heading2_size INTEGER NOT NULL DEFAULT 14,
    heading2_bold BOOLEAN NOT NULL DEFAULT true,
    heading2_italic BOOLEAN NOT NULL DEFAULT false,
    heading2_alignment VARCHAR(20) NOT NULL DEFAULT 'Left'::character varying,
    heading3_size INTEGER NOT NULL DEFAULT 13,
    heading3_bold BOOLEAN NOT NULL DEFAULT true,
    heading3_italic BOOLEAN NOT NULL DEFAULT false,
    heading3_alignment VARCHAR(20) NOT NULL DEFAULT 'Left'::character varying,
    hanging_indent NUMERIC NOT NULL DEFAULT 1.27,
    reference_spacing NUMERIC NOT NULL DEFAULT 2.00,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT fk_custom_formats_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ============================================================================
-- SEGURIDAD (Row Level Security - RLS)
-- ============================================================================
-- Supabase bloquea el acceso por defecto (403 Forbidden) si no hay políticas definidas.
-- Estas instrucciones habilitan RLS pero crean políticas completamente permisivas
-- para que puedas leer, insertar, actualizar y borrar sin problemas (modo desarrollo).

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_citation_formats ENABLE ROW LEVEL SECURITY;

-- Permitir TODO en la tabla users
CREATE POLICY "Permitir todo a todos en users" 
ON users FOR ALL 
USING (true) 
WITH CHECK (true);

-- Permitir TODO en la tabla custom_citation_formats
CREATE POLICY "Permitir todo a todos en custom_citation_formats" 
ON custom_citation_formats FOR ALL 
USING (true) 
WITH CHECK (true);

-- ============================================================================
-- PERMISOS BÁSICOS (Grants)
-- ============================================================================
-- Asegurar que los roles de la API de Supabase (anon y authenticated)
-- tengan permiso real sobre las tablas.
GRANT ALL ON TABLE public.users TO anon, authenticated;
GRANT ALL ON TABLE public.custom_citation_formats TO anon, authenticated;

-- ============================================================================
-- SINCRONIZACIÓN DE USUARIOS (Supabase Auth -> Public Users)
-- ============================================================================
-- Cuando te registras en Supabase, el usuario se crea en "auth.users" 
-- pero NO en "public.users" automáticamente. Esta función y trigger lo solucionan.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger que se dispara cada vez que alguien se registra
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================================================
-- ARREGLO PARA USUARIOS ACTUALES
-- ============================================================================
-- Copiar cualquier usuario que ya se haya registrado en Supabase hacia public.users
INSERT INTO public.users (id, email)
SELECT id, email FROM auth.users
ON CONFLICT (id) DO NOTHING;
